name: CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run docker compose
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login docker
        run: echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USER }}/blog:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_HUB_USER }}/blog:latest

      - name: Connect to server via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.PROJECT_PATH }}
            docker pull ${{ secrets.DOCKER_HUB_USER }}/blog:latest
            docker compose up -d
            docker image prune -f
